### ISSUE TITLE
Getting error when running subjs against URL's list

### ISSUE THREAD

**Issue by 0xdekster** [C0RB3N/subjs#10]
Getting error when running subjs against URL's list

Using it like this -> subjs -i urlslist.txt 

OUTPUT- 

github.com/lc/subjs/runner/subjs.(*SubJS).fetch(0xc000048c50, 0xc0000680c0, 0xc000068120)
	/root/go/src/github.com/lc/subjs/runner/subjs/runner.go:91 +0x1b1
github.com/lc/subjs/runner/subjs.(*SubJS).Run.func1(0xc000048c50, 0xc0000680c0, 0xc000068120, 0xc000018350)
	/root/go/src/github.com/lc/subjs/runner/subjs/runner.go:55 +0x3f
created by github.com/lc/subjs/runner/subjs.(*SubJS).Run
	/root/go/src/github.com/lc/subjs/runner/subjs/runner.go:54 +0x118

goroutine 7 [select]:
net/http.(*persistConn).roundTrip(0xc0bfd099e0, 0xc0bff25d40, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:2425 +0x770
net/http.(*Transport).roundTrip(0xc00009e280, 0xc0bff9eb00, 0xc0bff25d10, 0xc0bff6a43c, 0xc0bff6a430)
	/usr/local/go/src/net/http/transport.go:535 +0x9af
net/http.(*Transport).RoundTrip(0xc00009e280, 0xc0bff9eb00, 0xc00009e280, 0xbfa500c65f0f2a03, 0xa10f5a35c)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc0bff9ea00, 0x795aa0, 0xc00009e280, 0xbfa500c65f0f2a03, 0xa10f5a35c, 0x98bbc0, 0xc0bfab59c8, 0xbfa500c65f0f2a03, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:250 +0x443
net/http.(*Client).send(0xc000012f30, 0xc0bff9ea00, 0xbfa500c65f0f2a03, 0xa10f5a35c, 0x98bbc0, 0xc0bfab59c8, 0x0, 0x1, 0x71f1c0)
	/usr/local/go/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc000012f30, 0xc0bff9ea00, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:641 +0x3ce
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:509
github.com/lc/subjs/runner/subjs.(*SubJS).fetch(0xc000048c50, 0xc0000680c0, 0xc000068120)
	/root/go/src/github.com/lc/subjs/runner/subjs/runner.go:91 +0x1b1
github.com/lc/subjs/runner/subjs.(*SubJS).Run.func1(0xc000048c50, 0xc0000680c0, 0xc000068120, 0xc000018350)
	/root/go/src/github.com/lc/subjs/runner/subjs/runner.go:55 +0x3f
created by github.com/lc/subjs/runner/subjs.(*SubJS).Run
	/root/go/src/github.com/lc/subjs/runner/subjs/runner.go:54 +0x118

**Comment by lc** [comment]
Hey @0xn75ll, can you share what your `urlslist.txt` looks like?

**Comment by lc** [comment]
Hey @0xn75ll,

Thanks for opening this issue! This issue has been fixed in the latest release: https://github.com/lc/subjs/releases/tag/v1.0.1
