### ISSUE TITLE
subjs doesnt fetch all js files

### ISSUE THREAD

**Issue by ghost** [C0RB3N/subjs#11]
Hi, 
I recently had a case where the js file was referenced as 
<script type="text/javascript" src="app.js"></script> but subjs didn't fetch app.js 

I hope you'll have a look at this soon.
Best Regards,

**Comment by ghost** [comment]
Just tried the same process on the previous version of subjs and it works fine. Newer one seems to have the issue.

**Comment by lc** [comment]
Thanks @thuglifelulz, I had fixed #6 but introduced this bug. I'll take a look

**Comment by lc** [comment]
Hey @thuglifelulz,

I can confirm this issue, it might be an issue with the premature closing of channels, as some runs I am getting the app.js included and others not:

<img width="456" alt="Screen Shot 2020-05-16 at 11 24 51 AM" src="https://user-images.githubusercontent.com/19563282/82124905-e35a6800-9767-11ea-85c5-f8fcb4192a46.png">

**Comment by lc** [comment]
I'm missing a Wait(), will fix this

**Comment by lc** [comment]
Thanks for opening this issue, it has been fixed in the latest release:  https://github.com/lc/subjs/releases/tag/v1.0.1
