### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by ghost** [C0RB3N/subjs#3]
Great tool 👍👍.

However it would be great to implement [waybackurls](https://github.com/tomnomnom/waybackurls) to look for *forgotten js endpoints* for a domain and pass to linkfinder.

**Comment by lc** [comment]
This is a good idea, I do it separately in my workflow but this would likely save everyone time. I will probably implement this into the tool and require a flag such as `-wayback` in order to include those old JS files

**Comment by lc** [comment]
Just refactored the tool and added the `-wayback` flag to include javascript files from the wayback machine! Thanks for your suggestion!

**Comment by ghost** [comment]
We said Christmas doesnt come early.
Thanks a bunch
